openapi: 3.0.2
info:
  description: xx
  title: Yo
  version: 2019.0.1
servers:
  - url: host.com
paths:
  /req:
    get:
      operationId: goReq
      description: hi
      responses:
        '200':
          description: yay
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      kind:
                        type: string
                        enum:
                          - cat
                      content:
                        type: object
                        properties:
                          meow:
                            type: number

